// generated 2005/4/24 15:46:13 EDT by scott@Corwin.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/scott/projects/acovea-gtk/acovea-gtk.glade
// for gtk 2.4.14 and gtkmm 2.4.8
//
// Please modify the corresponding derived classes in ./src/about_box.hh and./src/about_box.cc

#ifndef _ABOUT_BOX_GLADE_HH
#  define _ABOUT_BOX_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/image.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/separator.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>

class about_box_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * about_box;
        class Gtk::Image * about_logo;
        class Gtk::Label * about_description_label;
        class Gtk::HBox * hbox1;
        class Gtk::HSeparator * hseparator1;
        class Gtk::Button * about_close_button;
        class Gtk::HButtonBox * hbuttonbox1;
        class Gtk::VBox * vbox3;
protected:
        
        about_box_glade();
        
        ~about_box_glade();
private:
        virtual void on_about_close_button_clicked() = 0;
        virtual void on_about_box_realize() = 0;
};
#endif
